version: '3.8'

services:
  db-estoque:
    image: postgres:16
    container_name: postgres-estoque
    environment:
      POSTGRES_DB: metalurgica_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: